plugins {
    id 'com.android.application'
}

android {
    namespace 'com.your.hook'
    compileSdk 34

    defaultConfig {
        applicationId "com.your.hook"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    // 使用 libxposed API（官方推荐）
    compileOnly 'io.github.libxposed:api:102.0.0'
}

